### ISSUE TITLE
First Milestone Release?

### ISSUE THREAD

**Issue by dzou** [justinhorvitz/quoridor#4]
Hi, just wanted to ask - what is the projected target date for the first milestone release?

Really excited to see quoridor in development, our team thinks its quite innovative, and we are excited to try using it.

**Comment by dzou** [comment]
Hi Justin,

Thanks for the response. Yes, indeed, I do have some recommendations for testing frameworks in this case.

At the unit test level, I strongly recommend usage of [Truth](https://github.com/google/truth), a fluent assertions library for Java, and Mockito, a mocking library for Java.

At the integration test level, I would recommend adopting a continuous Integration framework. Popular choices involve Travis or Jenkins. However, I wouldn't recommend simply choosing the default option; one ought to choose a CI based some research.

Here is a link about CI's: https://blog.github.com/2017-11-07-github-welcomes-all-ci-tools/

**Comment by justinhorvitz** [comment]
I will close this issue because your original question has been answered thoroughly. Thank you for your interest in this project.
